apiVersion: v1
kind: Namespace
metadata:
  name: chilensis

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chilensis-config
  namespace: chilensis
data:
  DB_HOST: "postgres-service"
  DB_USER: "admin"
  NATS_URL: "nats://nats-service:4222"
  TRADUCTOR_URL: "http://traductor-service:8080"
  SUGERENCIAS_URL: "http://sugerencias-service:3001"
  CONTEXTO_URL: "http://contexto-service:8082"
  DICCIONARIO_GRPC_ADDR: "diccionario-service:50051"
  CONTEXTO_GRPC_ADDR: "contexto-service:50052"

---
apiVersion: v1
kind: Secret
metadata:
  name: chilensis-secrets
  namespace: chilensis
type: Opaque
stringData:
  DB_PASSWORD: "admin_password"
  DATABASE_URL_TRADUCTOR: "postgres://admin:admin_password@postgres-service:5432/db_traductor"
  DATABASE_URL_DICCIONARIO: "postgres://admin:admin_password@postgres-service:5432/db_diccionario"
  DATABASE_URL_CONTEXTO: "postgres://admin:admin_password@postgres-service:5432/db_contexto"
  DATABASE_URL_SUGERENCIAS: "postgres://admin:admin_password@postgres-service:5432/db_sugerencias"
