spring.application.name=diccionario

spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:5432/db_diccionario
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:admin_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081